
 public class VariablesTheme {
     public static void main(String[] args) {
         System.out.println(" 1. Вывод значений переменных на консоль ");
         byte a = 12;
         System.out.println("\n.Количество ядер: " + a);
         short b = (short) 3;
         System.out.println(" \n. Частота процессора: " + b);
         int c = 7000;
         System.out.println("\n. Частота Шины: " + c);
         long d = 00331 - 10000 - 00001;
         System.out.println("\n. Код продукта: " + d);
         float i = 03_03;
         System.out.println("\n. Дата  установки: " + i);
         double f = 570;
         System.out.println("\n. Видеокарта: " + f);
         char ch1, ch2;
         ch1 = 932;
         ch2 = 220;
         System.out.println("\n. Объем  HDD:" + ch1);
         System.out.println("\n. Объем  SSD:" + ch2);
         boolean g = true;
         System.out.println("\n. Установлен ли Wibdows: " + g);
         System.out.println(" \n. 2. Расчет стоимости товара со скидкой");
         int x = 100;
         int y = 200;
         int I = x + y;
         int II = I / x * 11;
         int III = I - 33;
         System.out.println("\n. Общая стоимость товаров без скидки:" + I);
         System.out.println("\n. Сумма скидки:" + II);
         System.out.println("\n. Общая сумма товаров со скидкой:" + III);
         System.out.println("\n.  3.Вывод слова JAVA");
         System.out.println("   J    a  v     v  a     ");
         System.out.println("   J   a a  v   v  a a");
         System.out.println("J  J  aaaaa  V V  aaaaa");
         System.out.println(" JJ  a     a  V  a     a");
         System.out.println("\n.  4.Вывод min и max значений целых числовых типов");
         byte t1 = 127;
         byte t2 = 127;
         System.out.println("byte максимум:" + t1);
         t1++;
         System.out.println("byte инкремент:" + t1);
         t2--;
         System.out.println("byte дикремент: " + t2);
         short hp1 = 32_767;
         short hp2 = 32_767;
         System.out.println("short максимум:" + hp1);
         hp1++;
         System.out.println("short инкримент:" + hp1);
         hp2--;
         System.out.println("short дикримент:" + hp2);
         int gp = 2_147_483_647;
         int gp2 = 2_147_483_647;
         System.out.println("int максимум:" + gp);
         gp += 1;
         System.out.println("int инкримент:" + gp2);
         gp2 -= 1;
         System.out.println("int дикримент:" + gp2);
         long tp = 9_223_372_036_854_775_807L;
         long tp2 = 9_223_372_036_854_775_807L;
         System.out.println("long максимум:" + tp);
         tp += 1;
         System.out.println("long инкримент:" + tp2);
         tp2 -= 1;
         System.out.println("long дикримент:" + tp2);
         System.out.println("\n.  5.Перестановка значений переменных");
         int r1 = 2;
         int o1 = 5;
         System.out.println(" перестановка с помощью третьей переменной");
         System.out.println(" Изначальные значения: r1 = " + r1 + ", o1 = " + o1);
         int op1;
         op1 = r1;
         r1 = o1;
         o1 = op1;
         System.out.println(" Итоговое значение: r1 = " + r1 + ", o1 = " + o1);
         r1 += 3;
         o1 -= 3;
         op1 = r1;
         System.out.println(" перестановка с помощью арифметической операции");
         System.out.println(" Изначальные значения: r1 = " + r1 + ", o1 = " + o1);
         System.out.println("Итоговые значения:" + r1 + o1);
         System.out.println("Перестановка с помощью побитовой операции");
         int a1 = 2;
         int b2 = 5;
         int c3 = a1 ^ b2;
         a1 = c3 ^ a1;
         b2 = c3 ^ b2;
         System.out.println("\n Новые значения переменнх: a1 = " + a1 + " , b2 = " + b2);
         System.out.println("\n.  6.Вывод символов и их кодов");
         char q1, q2, q3, q4, q5;
         q1 = '#';
         q2 = '&';
         q3 = '@';
         q4 = '^';
         q5 = '_';
         System.out.println("Наименование:" + "символ:" + "Код:");
         System.out.println(q1 + " 35 ");
         System.out.println(q2 + " 38 ");
         System.out.println(q3 + " 64 ");
         System.out.println(q4 + " 94 ");
         System.out.println(q5 + " 95 ");
         System.out.println("\n.  7.Вывод в консоль ASCII-арт Дюка");
         char qq, qq1, qq2, qq3, qq4;
         qq = '\\';
         qq1 = '/';
         qq2 = '(';
         qq3 = ')';
         qq4 = '_';
         System.out.println("    " + qq1 + qq);
         System.out.println("   " + qq1 + "  " + qq);
         System.out.println("  " + qq1 + qq4 + qq2 + " " + qq3 + qq);
         System.out.println(" " + qq1 + "      " + qq);
         System.out.print(qq1);
         System.out.print(qq4);
         System.out.print(qq4);
         System.out.print(qq4);
         System.out.print(qq4);
         System.out.print(qq1);
         System.out.print(qq);
         System.out.print(qq4);
         System.out.print(qq4);
         System.out.print(qq);
         System.out.println("\n.  8.Вывод количества сотен, десятков и единиц числа");
         int N = 123;
         int X = N / 100;
         int Y = (N - (X * 100)) / 10;
         int Z = N % 10;
         System.out.print(" Число " + N + "состоит:\n ");
         System.out.print(X + " сотни\n " + Y + " десятки\n " + Z + " единицы\n ");
         int sum = X + Y + Z;
         int multiplication = X * Y * Z;
         System.out.println(" сумма его цифр: " + sum);
         System.out.println(" произведение: " + multiplication);
         System.out.println("\n.  9.Вывод времени");
         int second = 86399;
         int minutes = second / 60;
         int hours = minutes / 60;
         int seconds = minutes % 60;
         System.out.println(hours + ":" + minutes + ":" + seconds);

     }
 }

